### ISSUE TITLE
forex prediction

### ISSUE THREAD

**Issue by ericleonardo** [issaz/sigker-nsdes#1]
Hi, Zacharia!
Please, can this be used to predict forex EURUSD direction (up/down) one step ahead? Like next hour or day.
Congratulations for the work and thanks for sharing.

**Comment by issaz** [comment]
Hi Eric, 

Could you be more specific regarding the issue you have faced. Have you tried to use the conditional generator for the process y = ((t_0, y_{t_0}), (t_1, y_{t_1}) (as in, one timestep ahead) and it has not worked?

**Comment by ericleonardo** [comment]
Thanks you! I will try your suggestion y = ((t_0, y_{t_0}), (t_1, y_{t_1}) .
It is the first time I see something like this (more complex). I'm used to traditional machine learning approach to predict next step direction (using features and label to train).

Please, do you think possible to get at least 60% directional accuracy predicting next step with your algorithm? Or it is not adequate for this task?

**Comment by issaz** [comment]
Hi Eric, 

I am going to close this as it doesn't sound like you are discussing an issue with the code. 

If you have questions I would encourage you to reach out  via email. 

Zach
